# Generated by Django 5.2.9 on 2025-12-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='projectimage',
            table='project_images',
        ),
    ]
