# Generated by Django 5.2.9 on 2025-12-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriber',
            table='newsletter_subscribers',
        ),
    ]
