# Generated by Django 5.2.9 on 2025-12-14 23:37

import newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_subscriber_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(default=newsletter.models.generate_unsubscribe_token, editable=False, max_length=32, unique=True),
        ),
    ]
