"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mzv!m5c%vzx!=6d96dy25d79*bbaz02p%+(a@!x%$6l&(v2yw#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',    
    '192.168.1.159',
    'localhost',
    '0.0.0.0'
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://127.0.0.1:8000",
#     "http://192.168.1.159:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.159:3000",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = False  # True in production (HTTPS)
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = False


# Allow specific headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-device-id',  # Add this line to allow x-device-id header
]

# Allow credentials
CORS_ALLOW_CREDENTIALS = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Third-party apps
    'django_user_agents',
    'ckeditor',
    'rest_framework',
    'allauth',
    'allauth.account',
    'auth_kit',
    'corsheaders',
    
    # Local apps
    'contact',
    'projects',
    'blog',
    'newsletter',
    'users',
]

# Required for allauth
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Add this line
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'techshinobidb',
#         'USER': 'techshinobidb_user',
#         'PASSWORD': 'GR8mVphteYhELQvP5smnPnG1BeW9NjDE',
#         'HOST': 'postgresql://techshinobidb_user:GR8mVphteYhELQvP5smnPnG1BeW9NjDE@dpg-d56jiuu3jp1c73afc2jg-a.oregon-postgres.render.com/techshinobidb',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'techshinobidb',
        'USER': 'techshinobidb_user',
        'PASSWORD': 'GR8mVphteYhELQvP5smnPnG1BeW9NjDE',
        'HOST': 'dpg-d56jiuu3jp1c73afc2jg-a.oregon-postgres.render.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'your-smtp-server.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-email-password'
DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'
ADMIN_EMAIL = 'admin@yourdomain.com'  # Replace with admin email


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload permissions
FILE_UPLOAD_PERMISSIONS = 0o644



# REST Framework settings

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        # "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "auth_kit.authentication.JWTCookieAuthentication",  # enables cookie tokens
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 9
}

AUTH_USER_MODEL = "users.User"

# Authentication settings
# AUTHENTICATION_BACKENDS = [
#     # Needed to login by username in Django admin, regardless of `allauth`
#     'django.contrib.auth.backends.ModelBackend',

#     # `allauth` specific authentication methods, such as login by email
#     'allauth.account.auth_backends.AuthenticationBackend',
# ]

SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']


AUTH_KIT = {
    "AUTH_TYPE": "jwt",  # or 'token' if you prefer DRF tokens
    "USE_AUTH_COOKIE": True,  # enable cookie
    "SESSION_LOGIN": False,  # disable Django session login unless needed\
    "ALLOW_LOGIN_REDIRECT": False,
    "AUTH_COOKIE_NAME": "auth_token",  # default cookie name
    "AUTH_HEADER_TYPES": ("Bearer",),  # what the Authorization header expects
    # ===================================================================
    # COOKIE CONFIGURATION
    # ===================================================================
    "AUTH_COOKIE_SECURE": False,  # Require HTTPS for cookies
    "AUTH_COOKIE_HTTPONLY": True,  # Prevent JavaScript access
    "AUTH_COOKIE_SAMESITE": "Lax",  # 'Lax', 'Strict', or 'None'
    "AUTH_COOKIE_DOMAIN": None,  # Cookie domain
    # ===================================================================
    # JWT AUTHENTICATION SETTINGS
    # ===================================================================
    "AUTH_JWT_COOKIE_NAME": "auth-jwt",
    "AUTH_JWT_COOKIE_PATH": "/",
    "AUTH_JWT_REFRESH_COOKIE_NAME": "auth-refresh-jwt",
    "AUTH_JWT_REFRESH_COOKIE_PATH": "/",
    # ===================================================================
    # LOGIN & LOGOUT SERIALIZERS & VIEWS
    # ===================================================================
    "LOGIN_REQUEST_SERIALIZER": "auth_kit.serializers.login_factors.LoginRequestSerializer",
    "LOGIN_RESPONSE_SERIALIZER": "auth_kit.serializers.login_factors.BaseLoginResponseSerializer",
    "LOGIN_SERIALIZER_FACTORY": "auth_kit.serializers.login.get_login_serializer",
    "LOGIN_VIEW": "auth_kit.views.LoginView",
    "LOGOUT_SERIALIZER": "auth_kit.serializers.logout.AuthKitLogoutSerializer",
    "LOGOUT_VIEW": "auth_kit.views.LogoutView",
    # ===================================================================
    # USER MANAGEMENT SERIALIZERS & VIEWS
    # ===================================================================
    "USER_SERIALIZER": "users.serializers.UserDetailSerializer",
    "USER_VIEW": "auth_kit.views.UserView",
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Looking to send emails in production? Check out our Email API/SMTP product!
# EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
# EMAIL_HOST_USER = 'a1ed9b3cb00414'
# EMAIL_HOST_PASSWORD = '3929b68f9d634f'
# EMAIL_PORT = '2525'

# In settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Make sure this is set
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_PORT = 2525  # Should be an integer, not a string
EMAIL_USE_TLS = True  # Add this line
EMAIL_HOST_USER = 'a1ed9b3cb00414'  # Your Mailtrap username
EMAIL_HOST_PASSWORD = '3929b68f9d634f'  # Your Mailtrap password
DEFAULT_FROM_EMAIL = 'noreply@techshinobi.com'  # Set a default from email

# In settings.py
FRONTEND_URL = 'https://yourdomain.com'  # Your frontend URL
DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'  # Your default from email