# Generated by Django 5.2.9 on 2025-12-12 17:55

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_image_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
